# This is a basic workflow to help you get started with Actions

name: Emacs tests and linting

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 24.1
          - 24.2
          - 24.3
          - 24.4
          - 24.5
          - 25.1
          - 25.2
          - 25.3
          - 26.1
          - 26.2
          - 26.3
        ignore_warnings:
          - true
        include:
          - emacs_version: snapshot
            ignore_warnings: false
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}
        
      - name: Emacs Lisp Linting
        uses: leotaku/elisp-check@v1.0
        with:
          check: package-lint
          file: org-literate-config.el
          ignore_warnings: true
    
      - name: Tests
        uses: leotaku/elisp-check@v1.0
        with:
          check: ert
          file: tests/all-tests.el
          ignore_warnings: true
